#' @title Convert lm model to latex syntax.
#'
#' @description         This function takes in the model generated by glm function and returns the latex syntax of either population model or fitted model or both.
#'
#' @param glm_model         The glm model that will be converted.
#' @param glm_form          "log", "odds" or "prob" represents the model returned is either model in log form, model in terms of odds and model in terms of probabilities.
#' @param glm_type          "pop", "fit" or "both" represents the model returned is either population model, fitted model or both.
#' @param glm_round_num     Number of significant digits.
#'
#' @return              Print the relative latex syntax.

#' @describeIn          Main function for producing the latex syntax of logistic regression model.
glm2tex <- function(glm_model, glm_form, glm_type, glm_round_num) {

    # Checking if the model is generated by glm function and the parameter family
    # is binomial (logistic regression model).
    if (model$call[[1]] == "glm" & grepl("binomial", deparse(model$call$family))) {

        # Initialize the 2 strings for latex syntax.
        pop_str <- ""
        fit_str <- ""


        # Check if the model have categorical predictor, if so, generate an array
        # with the according variable names.
        if (length(model$xlevels) == 0) {
            cate_exist <- FALSE
        } else {
            cate_exist <- TRUE
            cate_name_vec <- rep("", sum(lengths(model$xlevels)))
            gen_index <- 1
            for (i in 1:length(model$xlevels)) {
                for (j in 1:length(model$xlevels[[i]])) {
                    cate_name_vec[gen_index] <- paste0(names(model$xlevels[i]), model$xlevels[[i]][j])
                    gen_index = gen_index + 1
                }
            }
        }

        # Looping for concatenating the individual predictor strings.
        for (i in 1:length(model$coefficients)) {
            iter_num <- 1
            temp_coef <- model$coefficients[i]

            # Replacing the underline with "-" which latex doesn't like.
            names(temp_coef) <- gsub("_", "-", names(temp_coef))

            # Detect and change the sign of the coefficients in fitted model.
            coef_sign <- ifelse(temp_coef >= 0, "+", "-")

            # Main loop which treat the intercept differently.
            if (i == 1) {

                # Initialize the two strings for latex syntax of
                # both population and fitted predictors.
                temp_pop_str <- paste0(" \\beta_0")
                temp_fit_str <- paste0(" \\text{",
                                       coef_sign,
                                       toString(round(ifelse(temp_coef >= 0,
                                                             temp_coef,
                                                             temp_coef * -1), digits=round_num)),
                                       "}")
            } else {
                lf_sym <- "x"
                rt_sym <- "x"

                # Dealing with the categorical predictor case.
                if (cate_exist == TRUE & names(temp_coef) %in% cate_name_vec) {
                    lf_sym <- "d"
                } else if (grepl(":", names(temp_coef))) {

                    # Seperate the interaction coefficients.
                    coef_name_lf <- gsub('(.*):.*', '\\1', names(temp_coef))
                    coef_name_rt <- gsub('.*:(.*)', '\\1', names(temp_coef))

                    # Dealing with the categorical predictor case.
                    if (coef_name_lf %in% cate_name_vec & !(coef_name_rt %in% cate_name_vec)) {
                        lf_sym <- "d"
                    } else if (coef_name_rt %in% cate_name_vec & !(coef_name_lf %in% cate_name_vec)) {
                        rt_sym <- "d"
                    } else if (coef_name_rt %in% cate_name_vec & coef_name_lf %in% cate_name_vec) {
                        lf_sym <- "d"
                        rt_sym <- "d"
                    }

                    temp_pop_str <- paste0(" + \\beta_{\\text{",
                                           names(temp_coef),
                                           "}} \\cdot ", lf_sym,
                                           "_{\\text{",
                                           coef_name_lf,
                                           "}} \\cdot ", rt_sym,
                                           "_{\\text{",
                                           coef_name_rt,
                                           "}} ")

                    temp_fit_str <- paste0(coef_sign,
                                           " \\text{",
                                           toString(round(ifelse(temp_coef >= 0,
                                                                 temp_coef,
                                                                 temp_coef * -1), digits=round_num)),
                                           "} \\cdot ", lf_sym,
                                           "_{\\text{",
                                           coef_name_lf,
                                           "}} \\cdot ", rt_sym,
                                           "_{\\text{",
                                           coef_name_rt,
                                           "}} ")


                }

                temp_pop_str <- paste0(" + \\beta_{\\text{",
                                       names(temp_coef),
                                       "}} \\cdot ", lf_sym,
                                       "_{\\text{",
                                       names(temp_coef),
                                       "}} ")
                temp_fit_str <- paste0(coef_sign,
                                       " \\text{",
                                       toString(round(ifelse(temp_coef >= 0,
                                                             temp_coef,
                                                             temp_coef * -1), digits=round_num)),
                                       "} \\cdot ", lf_sym,
                                       "_{\\text{",
                                       names(temp_coef),
                                       "}} ")
                iter_num <- iter_num + 1
            }

            # Paste the temp syntax to the string.
            pop_str <- paste0(pop_str, temp_pop_str)
            fit_str <- paste0(fit_str, temp_fit_str)
        }
    } else {
        if (model$call[[1]] != "glm") {
            stop("The model passed in is not generated by glm function.")
        } else if (!(grepl("binomial", deparse(model$call$family)))) {
            stop("The family parameter specified in glm function is not binomial related. i.e, Not logistic regression.")
        } else {
            stop("Unknown Issue with the model passed in, please report this issue on https://github.com/SecantZhang/rmodel2tex/issues")
        }
    }

    # Initialize the final strings for outputting.
    fit_log_str <- paste0("log(\\frac{p_i}{1-p_i}) =", fit_str)
    fit_ods_str <- paste0("\\frac{p_i}{1-p_i} = e^{", fit_str, "}")
    fit_prb_str <- paste0("p_i = \\frac{e^{", fit_str, "}}{1 + e^{", fit_str, "}}")
    pop_log_str <- paste0("log(\\frac{p_i}{1-p_i}) =", pop_str)
    pop_ods_str <- paste0("\\frac{p_i}{1-p_i} = e^{", pop_str, "}")
    pop_prb_str <- paste0("p_i = \\frac{e^{", pop_str, "}}{1 + e^{", pop_str, "}}")

    # Output the syntax.
    if (glm_type == "fit") {
        if (glm_form == "log") {
            cat(fit_log_str)
        } else if (glm_form == "odds") {
            cat(fit_ods_str)
        } else if (glm_form == "prob") {
            cat(fit_prb_str)
        } else {
            stop('Invalid input for the parameter form. Try "log", "ods" or "prob" instead.')
        }
    } else if (glm_type == "pop") {
        if (glm_form == "log") {
            cat(pop_log_str)
        } else if (glm_form == "odds") {
            cat(pop_ods_str)
        } else if (glm_form == "prob") {
            cat(pop_prb_str)
        } else {
            stop('Invalid input for the parameter form. Try "log", "ods" or "prob" instead.')
        }
    } else if (glm_type == "both") {
        if (glm_form == "log") {
            cat(fit_log_str)
            cat(pop_log_str)
        } else if (glm_form == "odds") {
            cat(fit_ods_str)
            cat(pop_ods_str)
        } else if (glm_form == "prob") {
            cat(fit_prb_str)
            cat(pop_prb_str)
        } else {
            stop('Invalid input for the parameter form. Try "log", "ods" or "prob" instead.')
        }
    } else {
        stop('Invalid input for parameter type. Try "fit", "pop" or "both".')
    }
}
