#' @title Convert lm model to latex syntax.
#'
#' @description This function takes in the model generated by lm function and returns the latex syntax of either population model or fitted model or both.
#'
#' @param model         The lm model that will be converted.
#' @param type          "pop" or "fit" or "both" represents the model returned is either population model, fitted model or both.
#' @param round_num     Number of significant digits.
#'
#' @return The relative latex syntax.
#'
#' @examples
#' lm2tex(model, "fit", 2)
#' lm2tex(model, "both", 5)


lm2tex <- function(model, type, round_num) {

    # Checking if the model is generated by lm function.
    if (model$call[[1]] == "lm") {

        # Initialize the two strings for latex syntax of both population and fitted model.
        pop_str <- paste(toString(model$call$formula[[2]]), "=", sep=" ")
        fit_str <- paste("\\hat{", toString(model$call$formula[[2]]), "} = ", sep="")

        # Check if the model have categorical predictor.
        if (length(model$xlevels) == 0) {
            cate_exist <- FALSE
        } else {
            cate_exist <- TRUE
            cate_name_vec <- rep("", sum(lengths(model$xlevels)))
            gen_index <- 1
            for (i in 1:length(model$xlevels)) {
                for (j in 1:length(model$xlevels[[i]])) {
                    cate_name_vec[gen_index] <- paste0(names(model$xlevels[i]), model$xlevels[[i]][j])
                    gen_index = gen_index + 1
                }
            }
        }

        # Looping for concatenating the individual predictor strings.
        for (i in 1:length(model$coefficients)) {
            iter_num <- 1
            temp_coef <- model$coefficients[i]
            coef_sign <- ifelse(temp_coef >= 0, "+", "-")

            # Main loop which treat the intercept differently.
            if (i == 1) {

                # Initialize the two strings for the latex syntax of
                # both population and fitted predictors.
                temp_pop_str <- paste0(" \\beta_{\\text{0}} ")
                temp_fit_str <- paste0(" \\text{",
                                    toString(round(temp_coef, digits=round_num)),
                                    "} ")
            } else {
                lf_sym <- "x"
                rt_sym <- "x"

                # Dealing with the categorical predictor case.
                if (cate_exist == TRUE & names(temp_coef) %in% cate_name_vec) {
                    lf_sym <- "d"
                } else if (grepl(":", names(temp_coef))) {

                    # Seperate the interaction coefficients.
                    coef_name_lf <- gsub('(.*):.*', '\\1', names(temp_coef))
                    coef_name_rt <- gsub('.*:(.*)', '\\1', names(temp_coef))

                    # Dealing with the categorical predictor case.
                    if (coef_name_lf %in% cate_name_vec & !(coef_name_rt %in% cate_name_vec)) {
                        lf_sym <- "d"
                    } else if (coef_name_rt %in% cate_name_vec & !(coef_name_lf %in% cate_name_vec)) {
                        rt_sym <- "d"
                    } else if (coef_name_rt %in% cate_name_vec & coef_name_lf %in% cate_name_vec) {
                        lf_sym <- "d"
                        rt_sym <- "d"
                    }

                    temp_pop_str <- paste0(" + \\beta_{\\text{",
                                           names(temp_coef),
                                           "}} \\cdot ", lf_sym,
                                           "_{\\text{",
                                           coef_name_lf,
                                           "}} \\cdot ", rt_sym,
                                           "_{\\text{",
                                           coef_name_rt,
                                           "}} ")
                    temp_fit_str <- paste0(coef_sign,
                                           " \\text{",
                                           toString(round(ifelse(temp_coef >= 0,
                                                                 temp_coef,
                                                                 temp_coef * -1), digits=round_num)),
                                           "} \\cdot ", lf_sym,
                                           "_{\\text{",
                                           coef_name_lf,
                                           "}} \\cdot ", rt_sym,
                                           "_{\\text{",
                                           coef_name_rt,
                                           "}} ")
                }

                temp_pop_str <- paste0(" + \\beta_{\\text{",
                                       names(temp_coef),
                                       "}} \\cdot ", lf_sym,
                                       "_{\\text{",
                                       names(temp_coef),
                                       "}} ")
                temp_fit_str <- paste0(coef_sign,
                                       " \\text{",
                                       toString(round(ifelse(temp_coef >= 0,
                                                             temp_coef,
                                                             temp_coef * -1), digits=round_num)),
                                       "} \\cdot ", lf_sym,
                                       "_{\\text{",
                                       names(temp_coef),
                                       "}} ")

                iter_num <- iter_num + 1
            }

            # Paste the temp syntax to the string.
            pop_str <- paste0(pop_str, temp_pop_str)
            fit_str <- paste0(fit_str, temp_fit_str)
        }
    } else {
        stop("The model is not a linear regression model generated by lm function, try to use other parameters instead")
    }

    # Output the syntax.
    if (type == "fit") {
        cat(fit_str)
    } else if (type == "pop") {
        cat(pop_str)
    } else if (type == "both") {
        cat(fit_str)
        cat(pop_str)
    }
}
