#' @title Convert various model in r to latex syntax.
#'
#' @description
#'
#' @param model         the model that will be converted.
#' @param model_name    the name of the function used for generate the model.
#' @param type          population model or fitted model.
#' @param round_num     number of significant digits.
#'
#' @return
#'
#' @examples
#'
#' @export

rm2tex <- function(model, model_name, type, round_num) {
    if (type == "lm") {
        tex_str <- fun.lm(model, type, round_num)
    }

}

fun.lm <- function(model, type, round_num) {

    # Checking the if the model is generated by lm function.
    if (model$call[[1]] == "lm") {

        # Initialize the two strings for latex syntax of both population and fitted model.
        pop_str <- cat(toString(model$call$formula[[2]]), "=", sep=" ")
        fit_str <- cat("\\hat{", toString(model$call$formula[[2]]), "} = ", sep="")

        # Looping for concatenating the individual predictor strings.
        for (i in 1:length(model$coefficients)) {
            temp_coef <- model$coefficients[i]

            # Main loop which treat the intercept differently.
            if (i == 1) {

                # Initialize the two strings for the latex syntax of
                # both population and fitted predictors.
                temp_pop_str <- cat(" \\beta_{\\text{0}} ", sep="")
                temp_fit_str <- cat(" \\text{",
                                    toString(round(temp_coef, digits=round_num)),
                                    "} ", sep="")
            } else {
                temp_pop_str <- cat(" \\beta{\\text")
            }
        }
    } else {
        stop("The model is not a linear regression model generated by lm function, try to use other parameters instead")
    }
}
